# Generated by Django 4.2 on 2023-04-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_album_spotlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotlight",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotlight",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
